services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keycloak-keystore.p12
      - KC_HTTPS_KEY_STORE_PASSWORD=password
      - KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/conf/truststore.jks
      - KC_HTTPS_TRUST_STORE_PASSWORD=password
      - KC_HTTPS_CLIENT_AUTH=request
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:z
      - ./certs:/opt/keycloak/conf:z
    command: start-dev --import-realm

